export const productsData = {
	Vegetables: [
		{
			id: 95,
			name: 'Tomato',
			price: 90,
			discounted_price: 50,
			description:
				'Tomatoes are juicy fruits commonly used as vegetables in cooking. They are rich in lycopene, an antioxidant that has been linked to various health benefits.',
			rating: 4.3,
			stock: 826,
			category: 'Vegetables',
			image:
				'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/tomotos.webp',
		},
		{
			id: 96,
			name: 'Carrot',
			price: 60,
			discounted_price: 45,
			description:
				'Carrots are root vegetables that are rich in beta-carotene, which is converted into vitamin A in the body. They are crunchy and sweet when raw and can be cooked in various dishes.',
			rating: 4.1,
			stock: 769,
			category: 'Vegetables',
			image: '../images/carrots.jpg',
		},
		{
			id: 97,
			name: 'Broccoli',
			price: 120,
			discounted_price: 100,
			description:
				'Broccoli is a cruciferous vegetable known for its dense green florets. It is rich in vitamins, minerals, and antioxidants, making it a nutritious addition to any diet.',
			rating: 4.4,
			stock: 767,
			category: 'Vegetables',
			image:
				'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/broccoli.jpg?updatedAt=1712129712159',
		},
		{
			id: 98,
			name: 'Spinach',
			price: 80,
			discounted_price: 70,
			description:
				'Spinach is a leafy green vegetable packed with nutrients such as iron, calcium, and vitamins A and C. It can be eaten raw in salads or cooked in various dishes.',
			rating: 4.2,
			stock: 554,
			category: 'Vegetables',
			image: '../images/spinach.jpg',
		},
		{
			id: 99,
			name: 'Cucumber',
			price: 40,
			discounted_price: 35,
			description:
				'Cucumbers are cylindrical green fruits with a mild flavor and high water content. They are often eaten raw in salads or used as a refreshing snack.',
			rating: 4.3,
			stock: 811,
			category: 'Vegetables',
			image: '../images/cucumber.jpg',
		},
		{
			id: 100,
			name: 'Bell Pepper',
			price: 70,
			discounted_price: 60,
			description:
				'Bell peppers, also known as sweet peppers, come in various colors such as red, yellow, and green. They are crunchy and sweet, and can be eaten raw or cooked in a variety of dishes.',
			rating: 4.4,
			stock: 836,
			category: 'Vegetables',
			image:
				'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/bell-pepper-capsicum.jpg',
		},
		{
			id: 101,
			name: 'Potato',
			price: 50,
			discounted_price: 40,
			description:
				'Potatoes are starchy tuberous vegetables that are a staple food in many cuisines around the world. They can be boiled, baked, fried, or mashed, and are used in numerous dishes.',
			rating: 4,
			stock: 645,
			category: 'Vegetables',
			image: '../images/potato.jpg',
		},
		{
			id: 102,
			name: 'Lettuce',
			price: 30,
			discounted_price: 25,
			description:
				'Lettuce is a leafy green vegetable often used as a base for salads. It comes in various types, including iceberg, romaine, and leaf lettuce.',
			rating: 4.4,
			stock: 807,
			category: 'Vegetables',
			image: '../images/lettuce.jpg',
		},
		{
			id: 103,
			name: 'Onion',
			price: 45,
			discounted_price: 40,
			description:
				'Onions are aromatic vegetables with layers of flesh surrounding a central core. They are widely used in cooking to add flavor to various dishes.',
			rating: 4.4,
			stock: 511,
			category: 'Vegetables',
			image: '../images/onion.jpg',
		},
		{
			id: 104,
			name: 'Zucchini',
			price: 55,
			discounted_price: 50,
			description:
				'Zucchini, also known as courgette, is a summer squash with a mild flavor. It can be grilled, roasted, sautéed, or used in baking.',
			rating: 4.3,
			stock: 620,
			category: 'Vegetables',
			image: '../images/zucchini.jpg',
		},
		{
			id: 105,
			name: 'Eggplant',
			price: 65,
			discounted_price: 60,
			description:
				'Eggplant, also known as aubergine, is a versatile vegetable commonly used in Mediterranean and Asian cuisines. It has a meaty texture and absorbs flavors well when cooked.',
			rating: 4.2,
			stock: 899,
			category: 'Vegetables',
			image: '../images/eggplant.jpg',
		},
		{
			id: 106,
			name: 'Green Beans',
			price: 75,
			discounted_price: 70,
			description:
				'Green beans, also known as string beans or snap beans, are long, slender vegetables with a crisp texture. They can be steamed, stir-fried, boiled, or roasted.',
			rating: 4.5,
			stock: 630,
			category: 'Vegetables',
			image: '../images/green_beans.jpg',
		},
		{
			id: 107,
			name: 'Cabbage',
			price: 55,
			discounted_price: 50,
			description:
				'Cabbage is a leafy green or purple vegetable with dense leaves that can be eaten raw, cooked, or fermented. It is commonly used in salads, coleslaw, stir-fries, and soups.',
			rating: 4.5,
			stock: 703,
			category: 'Vegetables',
			image: '../images/cabbage.jpg',
		},
		{
			id: 108,
			name: 'Celery',
			price: 40,
			discounted_price: 35,
			description:
				'Celery is a crunchy, low-calorie vegetable with long stalks and a mild, slightly bitter flavor. It is often used as a snack, in salads, or as a flavoring agent in soups and stews.',
			rating: 4.1,
			stock: 981,
			category: 'Vegetables',
			image: '../images/celery.jpg',
		},
		{
			id: 109,
			name: 'Mushroom',
			price: 70,
			discounted_price: 60,
			description:
				'Mushrooms are fungi with a unique flavor and texture. They come in various types, including button, portobello, and shiitake, and can be used in a wide range of dishes, from soups and stir-fries to pizzas and pastas.',
			rating: 4.1,
			stock: 928,
			category: 'Vegetables',
			image: '../images/mushroom.jpg',
		},
		{
			id: 110,
			name: 'Cauliflower',
			price: 65,
			discounted_price: 60,
			description:
				'Cauliflower is a versatile vegetable with a mild, slightly nutty flavor. It can be eaten raw, roasted, steamed, or mashed, and is often used as a low-carb alternative to grains and legumes.',
			rating: 4.4,
			stock: 627,
			category: 'Vegetables',
			image: '../images/cauliflower.jpg',
		},
		{
			id: 111,
			name: 'Asparagus',
			price: 90,
			discounted_price: 80,
			description:
				'Asparagus is a spring vegetable with long, tender spears and a delicate flavor. It can be steamed, grilled, roasted, or sautéed, and is often served as a side dish or added to salads and omelets.',
			rating: 4.3,
			stock: 769,
			category: 'Vegetables',
			image: '../images/asparagus.jpg',
		},
		{
			id: 112,
			name: 'Sweet Potato',
			price: 80,
			discounted_price: 70,
			description:
				'Sweet potatoes are root vegetables with a sweet and starchy taste. They come in various colors, including orange, purple, and white. Sweet potatoes are rich in vitamins, minerals, and antioxidants, making them a nutritious addition to any diet.',
			rating: 4.1,
			stock: 828,
			category: 'Vegetables',
			image: '../images/sweet_potato.jpg',
		},
		{
			id: 113,
			name: 'Radish',
			price: 40,
			discounted_price: 35,
			description:
				'Radishes are small, crunchy vegetables with a peppery flavor. They come in various colors, shapes, and sizes and can be eaten raw or cooked. Radishes are low in calories and high in fiber, making them a healthy snack or addition to salads.',
			rating: 4.3,
			stock: 726,
			category: 'Vegetables',
			image: '../images/radish.jpg',
		},
		{
			id: 114,
			name: 'Beetroot',
			price: 60,
			discounted_price: 55,
			description:
				'Beetroots, also known as beets, are root vegetables with a sweet and earthy flavor. They come in various colors, including red, yellow, and striped, and can be eaten raw, cooked, or pickled. Beetroots are rich in vitamins, minerals, and antioxidants, making them a nutritious and versatile ingredient.',
			rating: 4.2,
			stock: 944,
			category: 'Vegetables',
			image: '../images/beetroot.jpg',
		},
		{
			id: 115,
			name: 'Artichoke',
			price: 100,
			discounted_price: 90,
			description:
				'Artichokes are large, thistle-like vegetables with tender, edible hearts and leaves. They have a mild, slightly nutty flavor and can be steamed, boiled, grilled, or roasted. Artichokes are rich in fiber, vitamins, and minerals, making them a healthy and delicious addition to any meal.',
			rating: 4.4,
			stock: 809,
			category: 'Vegetables',
			image: '../images/artichoke.jpg',
		},
		{
			id: 116,
			name: 'Okra',
			price: 70,
			discounted_price: 65,
			description:
				"Okra, also known as lady's fingers, is a green, pod-shaped vegetable with a unique flavor and texture. It is often used in soups, stews, and curries, and can also be fried, roasted, or pickled. Okra is low in calories and rich in fiber, vitamins, and minerals, making it a nutritious and versatile ingredient.",
			rating: 4.5,
			stock: 850,
			category: 'Vegetables',
			image: '../images/okra.jpg',
		},
		{
			id: 117,
			name: 'Kale',
			price: 50,
			discounted_price: 45,
			description:
				'Kale is a leafy green vegetable that belongs to the cabbage family. It has a slightly bitter taste and is packed with nutrients like vitamins A, C, and K, as well as antioxidants. Kale can be eaten raw in salads, sautéed, or added to soups and smoothies.',
			rating: 4.3,
			stock: 960,
			category: 'Vegetables',
			image: '../images/kale.jpg',
		},
		{
			id: 118,
			name: 'Brussels Sprouts',
			price: 70,
			discounted_price: 60,
			description:
				'Brussels sprouts are small, green cruciferous vegetables that resemble mini cabbages. They have a slightly bitter taste and are rich in vitamins K and C, as well as fiber and antioxidants. Brussels sprouts can be roasted, sautéed, or steamed and are often served as a side dish.',
			rating: 4.1,
			stock: 801,
			category: 'Vegetables',
			image: '../images/brussels_sprouts.jpg',
		},
		{
			id: 119,
			name: 'Watercress',
			price: 70,
			discounted_price: 65,
			description:
				'Watercress is a leafy green vegetable with a peppery flavor and a crisp, crunchy texture. It can be eaten raw in salads or sandwiches, or used as a garnish for soups and stews. Watercress is rich in vitamins, minerals, and antioxidants.',
			rating: 4.5,
			stock: 567,
			category: 'Vegetables',
			image: '../images/watercress.jpg',
		},
		{
			id: 120,
			name: 'Pumpkin',
			price: 80,
			discounted_price: 70,
			description:
				'Pumpkin is a type of winter squash with a sweet, nutty flavor. It is rich in vitamins A and C, as well as fiber and antioxidants. Pumpkin can be roasted, baked, steamed, or pureed and is commonly used in soups, stews, pies, and desserts.',
			rating: 4.3,
			stock: 785,
			category: 'Vegetables',
			image: '../images/pumpkin.jpg',
		},
		{
			id: 121,
			name: 'Corn',
			price: 45,
			discounted_price: 40,
			description:
				'Corn, also known as maize, is a cereal grain that is widely consumed as a staple food. It is rich in carbohydrates and fiber, as well as vitamins and minerals. Corn can be eaten fresh, cooked, or dried and is used in a variety of dishes, including salads, soups, and stir-fries.',
			rating: 4.1,
			stock: 687,
			category: 'Vegetables',
			image: '../images/corn.jpg',
		},
		{
			id: 122,
			name: 'Celeriac',
			price: 55,
			discounted_price: 50,
			description:
				'Celeriac, also known as celery root, is a root vegetable with a bulbous, knobby appearance. It has a mild, celery-like flavor and is often used in soups, stews, and purees. Celeriac is rich in vitamins, minerals, and dietary fiber.',
			rating: 4.2,
			stock: 806,
			category: 'Vegetables',
			image: '../images/celeriac.jpg',
		},
		{
			id: 123,
			name: 'Turnip',
			price: 50,
			discounted_price: 45,
			description:
				'Turnips are root vegetables with a slightly spicy flavor and a crunchy texture. They can be eaten raw, cooked, or pickled and are often used in soups, stews, and salads. Turnips are low in calories and rich in vitamins, minerals, and antioxidants.',
			rating: 4.4,
			stock: 936,
			category: 'Vegetables',
			image: '../images/turnip.jpg',
		},
		{
			id: 124,
			name: 'Rutabaga',
			price: 60,
			discounted_price: 55,
			description:
				'Rutabagas, also known as swedes, are root vegetables that are a cross between turnips and cabbage. They have a slightly sweet and earthy flavor and can be eaten raw, roasted, boiled, or mashed. Rutabagas are rich in vitamins, minerals, and fiber.',
			rating: 4.3,
			stock: 836,
			category: 'Vegetables',
			image: '../images/rutabaga.jpg',
		},
		{
			id: 125,
			name: 'Kohlrabi',
			price: 65,
			discounted_price: 60,
			description:
				'Kohlrabi is a bulbous vegetable with a mild, sweet flavor and a crisp, crunchy texture. It can be eaten raw or cooked and is often used in salads, slaws, and stir-fries. Kohlrabi is rich in vitamins, minerals, and antioxidants.',
			rating: 4.4,
			stock: 903,
			category: 'Vegetables',
			image: '../images/kohlrabi.jpg',
		},
	],
	Fruits: [
		{
			id: 126,
			name: 'Apple',
			price: 80,
			discounted_price: 70,
			description:
				'Apples are crisp and juicy fruits with a sweet and slightly tart flavor. They come in various colors and are rich in fiber, vitamins, and antioxidants.',
			rating: 4.1,
			stock: 909,
			category: 'Fruits',
			image: '../images/apple.jpg',
		},
		{
			id: 127,
			name: 'Banana',
			price: 60,
			discounted_price: 50,
			description:
				'Bananas are creamy and sweet fruits with a soft texture. They are rich in potassium, vitamins, and dietary fiber, making them a healthy snack option.',
			rating: 4.2,
			stock: 520,
			category: 'Fruits',
			image: '../images/banana.jpg',
		},
		{
			id: 128,
			name: 'Orange',
			price: 70,
			discounted_price: 60,
			description:
				'Oranges are citrus fruits with a bright and tangy flavor. They are rich in vitamin C, antioxidants, and fiber, making them a refreshing and nutritious snack.',
			rating: 4.1,
			stock: 960,
			category: 'Fruits',
			image: '../images/orange.jpg',
		},
		{
			id: 129,
			name: 'Grapes',
			price: 100,
			discounted_price: 90,
			description:
				'Grapes are small, sweet fruits that grow in clusters on vines. They come in various colors, including green, red, and purple, and are often eaten fresh or used to make wine, juice, or jelly.',
			rating: 4.3,
			stock: 866,
			category: 'Fruits',
			image: '../images/grapes.jpg',
		},
		{
			id: 130,
			name: 'Strawberry',
			price: 120,
			discounted_price: 110,
			description:
				'Strawberries are juicy, red berries with a sweet and slightly tart flavor. They are rich in vitamin C, antioxidants, and dietary fiber, making them a popular and nutritious snack.',
			rating: 4.3,
			stock: 809,
			category: 'Fruits',
			image:
				'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/strawberry.jpg',
		},
		{
			id: 131,
			name: 'Pineapple',
			price: 150,
			discounted_price: 140,
			description:
				'Pineapples are tropical fruits with a sweet and tangy flavor. They are rich in vitamin C, manganese, and bromelain, an enzyme that may have anti-inflammatory properties.',
			rating: 4.2,
			stock: 798,
			category: 'Fruits',
			image: '../images/pineapple.jpg',
		},
		{
			id: 132,
			name: 'Mango',
			price: 100,
			discounted_price: 90,
			description:
				'Mangoes are juicy, tropical fruits with a sweet and tangy flavor. They are rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.3,
			stock: 797,
			category: 'Fruits',
			image: '../images/mango.jpg',
		},
		{
			id: 133,
			name: 'Watermelon',
			price: 80,
			discounted_price: 70,
			description:
				'Watermelons are large, juicy fruits with a sweet and refreshing flavor. They are high in water content and rich in vitamins A and C, as well as antioxidants.',
			rating: 4.3,
			stock: 968,
			category: 'Fruits',
			image: '../images/watermelon.jpg',
		},
		{
			id: 134,
			name: 'Kiwi',
			price: 60,
			discounted_price: 50,
			description:
				'Kiwi, also known as Chinese gooseberry, is a small, fuzzy fruit with a sweet and tart flavor. It is rich in vitamin C, vitamin K, and dietary fiber.',
			rating: 4.4,
			stock: 562,
			category: 'Fruits',
			image: '../images/kiwi.jpg',
		},
		{
			id: 135,
			name: 'Peach',
			price: 90,
			discounted_price: 80,
			description:
				'Peaches are soft, juicy fruits with a sweet and slightly tangy flavor. They are rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.2,
			stock: 762,
			category: 'Fruits',
			image: '../images/peach.jpg',
		},
		{
			id: 136,
			name: 'Pear',
			price: 70,
			discounted_price: 60,
			description:
				'Pears are sweet and juicy fruits with a slightly grainy texture. They come in various colors and are rich in vitamins C and K, as well as dietary fiber.',
			rating: 4.1,
			stock: 877,
			category: 'Fruits',
			image: '../images/pear.jpg',
		},
		{
			id: 137,
			name: 'Plum',
			price: 80,
			discounted_price: 70,
			description:
				'Plums are small, sweet fruits with a smooth, often purple skin and a juicy flesh. They are rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.1,
			stock: 989,
			category: 'Fruits',
			image: '../images/plum.jpg',
		},
		{
			id: 138,
			name: 'Cherry',
			price: 100,
			discounted_price: 90,
			description:
				'Cherries are small, round fruits with a sweet and tart flavor. They come in various colors, including red, yellow, and black, and are rich in vitamins, antioxidants, and dietary fiber.',
			rating: 4.4,
			stock: 715,
			category: 'Fruits',
			image: '../images/cherry.jpg',
		},
		{
			id: 139,
			name: 'Blueberry',
			price: 120,
			discounted_price: 110,
			description:
				'Blueberries are small, round berries with a sweet and tangy flavor. They are rich in antioxidants, vitamins, and dietary fiber, and are often eaten fresh or used in baking.',
			rating: 4.2,
			stock: 935,
			category: 'Fruits',
			image: '../images/blueberry.jpg',
		},
		{
			id: 140,
			name: 'Raspberry',
			price: 110,
			discounted_price: 100,
			description:
				'Raspberries are small, delicate berries with a sweet and slightly tart flavor. They are rich in antioxidants, vitamins, and dietary fiber, and are often eaten fresh or used in desserts and jams.',
			rating: 4.1,
			stock: 736,
			category: 'Fruits',
			image: '../images/raspberry.jpg',
		},
		{
			id: 141,
			name: 'Blackberry',
			price: 130,
			discounted_price: 120,
			description:
				'Blackberries are dark, juicy berries with a sweet and slightly tart flavor. They are rich in antioxidants, vitamins, and dietary fiber, and are often eaten fresh or used in desserts and smoothies.',
			rating: 4.3,
			stock: 762,
			category: 'Fruits',
			image: '../images/blackberry.jpg',
		},
		{
			id: 142,
			name: 'Apricot',
			price: 90,
			discounted_price: 80,
			description:
				'Apricots are small, golden-orange fruits with a sweet and slightly tart flavor. They are rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.2,
			stock: 924,
			category: 'Fruits',
			image: '../images/apricot.jpg',
		},
		{
			id: 143,
			name: 'Cantaloupe',
			price: 80,
			discounted_price: 70,
			description:
				'Cantaloupes, also known as muskmelons or rockmelons, are sweet and juicy fruits with a soft, orange flesh and a rough, netted skin. They are rich in vitamins A and C, as well as antioxidants.',
			rating: 4.1,
			stock: 740,
			category: 'Fruits',
			image: '../images/cantaloupe.jpg',
		},
		{
			id: 144,
			name: 'Honeydew Melon',
			price: 85,
			discounted_price: 75,
			description:
				'Honeydew melons are sweet and juicy fruits with a pale green flesh and a smooth, waxy skin. They are rich in vitamins C and K, as well as antioxidants.',
			rating: 4.5,
			stock: 755,
			category: 'Fruits',
			image: '../images/honeydew_melon.jpg',
		},
		{
			id: 145,
			name: 'Grapefruit',
			price: 70,
			discounted_price: 60,
			description:
				'Grapefruits are citrus fruits with a tart and tangy flavor. They come in various colors, including pink, red, and white, and are rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.1,
			stock: 666,
			category: 'Fruits',
			image: '../images/grapefruit.jpg',
		},
	],
	Juices: [
		{
			id: 146,
			name: 'Apple Juice',
			price: 100,
			discounted_price: 90,
			description:
				'Apple juice is a refreshing beverage made from pressed apples. It has a sweet and tangy flavor and is rich in vitamins and antioxidants.',
			rating: 4.4,
			stock: 980,
			category: 'Juices',
			image: '../images/apple_juice.jpg',
		},
		{
			id: 147,
			name: 'Banana Smoothie',
			price: 120,
			discounted_price: 110,
			description:
				'Banana smoothie is a creamy beverage made from blended bananas and other ingredients such as yogurt, milk, or fruit juice. It is rich in potassium, vitamins, and protein.',
			rating: 4.4,
			stock: 750,
			category: 'Juices',
			image: '../images/banana_smoothie.jpg',
		},
		{
			id: 148,
			name: 'Orange Juice',
			price: 90,
			discounted_price: 80,
			description:
				'Orange juice is a refreshing beverage made from squeezed oranges. It has a bright and tangy flavor and is rich in vitamin C and antioxidants.',
			rating: 4,
			stock: 890,
			category: 'Juices',
			image: '../images/orange_juice.jpg',
		},
		{
			id: 149,
			name: 'Grape Juice',
			price: 110,
			discounted_price: 100,
			description:
				'Grape juice is a sweet and flavorful beverage made from pressed grapes. It is rich in antioxidants and vitamins and is often enjoyed as a refreshing drink.',
			rating: 4.4,
			stock: 661,
			category: 'Juices',
			image: '../images/grape_juice.jpg',
		},
		{
			id: 150,
			name: 'Strawberry Smoothie',
			price: 130,
			discounted_price: 120,
			description:
				'Strawberry smoothie is a creamy and fruity beverage made from blended strawberries, yogurt, milk, or juice. It is rich in vitamin C, antioxidants, and dietary fiber.',
			rating: 4.3,
			stock: 500,
			category: 'Juices',
			image: '../images/strawberry_smoothie.jpg',
		},
		{
			id: 151,
			name: 'Pineapple Juice',
			price: 120,
			discounted_price: 110,
			description:
				'Pineapple juice is a tropical beverage made from squeezed pineapples. It has a sweet and tangy flavor and is rich in vitamin C, manganese, and bromelain.',
			rating: 4.2,
			stock: 705,
			category: 'Juices',
			image: '../images/pineapple_juice.jpg',
		},
		{
			id: 152,
			name: 'Mango Smoothie',
			price: 140,
			discounted_price: 130,
			description:
				'Mango smoothie is a creamy and tropical beverage made from blended mangoes, yogurt, milk, or juice. It is rich in vitamins A and C, antioxidants, and dietary fiber.',
			rating: 4,
			stock: 673,
			category: 'Juices',
			image: '../images/mango_smoothie.jpg',
		},
		{
			id: 153,
			name: 'Watermelon Juice',
			price: 100,
			discounted_price: 90,
			description:
				'Watermelon juice is a refreshing beverage made from squeezed watermelons. It has a sweet and hydrating flavor and is rich in vitamins A and C, as well as antioxidants.',
			rating: 4.4,
			stock: 697,
			category: 'Juices',
			image: '../images/watermelon_juice.jpg',
		},
		{
			id: 154,
			name: 'Kiwi Smoothie',
			price: 110,
			discounted_price: 100,
			description:
				'Kiwi smoothie is a creamy and tangy beverage made from blended kiwis, yogurt, milk, or juice. It is rich in vitamin C, vitamin K, and dietary fiber.',
			rating: 4.3,
			stock: 878,
			category: 'Juices',
			image: '../images/kiwi_smoothie.jpg',
		},
		{
			id: 155,
			name: 'Peach Juice',
			price: 95,
			discounted_price: 85,
			description:
				'Peach juice is a flavorful beverage made from squeezed peaches. It has a sweet and slightly tart flavor and is rich in vitamins A and C, as well as antioxidants.',
			rating: 4.5,
			stock: 593,
			category: 'Juices',
			image: '../images/peach_juice.jpg',
		},
		{
			id: 156,
			name: 'Pear Smoothie',
			price: 105,
			discounted_price: 95,
			description:
				'Pear smoothie is a creamy and sweet beverage made from blended pears, yogurt, milk, or juice. It is rich in vitamins C and K, as well as dietary fiber.',
			rating: 4.4,
			stock: 848,
			category: 'Juices',
			image: '../images/pear_smoothie.jpg',
		},
		{
			id: 157,
			name: 'Plum Juice',
			price: 100,
			discounted_price: 90,
			description:
				'Plum juice is a flavorful beverage made from pressed plums. It has a sweet and tangy flavor and is rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.4,
			stock: 573,
			category: 'Juices',
			image: '../images/plum_juice.jpg',
		},
		{
			id: 158,
			name: 'Cherry Smoothie',
			price: 120,
			discounted_price: 110,
			description:
				'Cherry smoothie is a creamy and fruity beverage made from blended cherries, yogurt, milk, or juice. It is rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.3,
			stock: 635,
			category: 'Juices',
			image: '../images/cherry_smoothie.jpg',
		},
		{
			id: 159,
			name: 'Blueberry Juice',
			price: 110,
			discounted_price: 100,
			description:
				'Blueberry juice is a sweet and tangy beverage made from squeezed blueberries. It is rich in antioxidants, vitamins, and dietary fiber, and is often enjoyed as a refreshing drink.',
			rating: 4.5,
			stock: 973,
			category: 'Juices',
			image: '../images/blueberry_juice.jpg',
		},
		{
			id: 160,
			name: 'Raspberry Smoothie',
			price: 125,
			discounted_price: 115,
			description:
				'Raspberry smoothie is a creamy and tangy beverage made from blended raspberries, yogurt, milk, or juice. It is rich in antioxidants, vitamins, and dietary fiber.',
			rating: 4.1,
			stock: 746,
			category: 'Juices',
			image: '../images/raspberry_smoothie.jpg',
		},
		{
			id: 161,
			name: 'Blackberry Juice',
			price: 115,
			discounted_price: 105,
			description:
				'Blackberry juice is a sweet and flavorful beverage made from pressed blackberries. It is rich in antioxidants, vitamins, and dietary fiber, and is often enjoyed as a refreshing drink.',
			rating: 4.3,
			stock: 801,
			category: 'Juices',
			image: '../images/blackberry_juice.jpg',
		},
		{
			id: 162,
			name: 'Apricot Smoothie',
			price: 130,
			discounted_price: 120,
			description:
				'Apricot smoothie is a creamy and fruity beverage made from blended apricots, yogurt, milk, or juice. It is rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.3,
			stock: 911,
			category: 'Juices',
			image: '../images/apricot_smoothie.jpg',
		},
		{
			id: 163,
			name: 'Cantaloupe Juice',
			price: 105,
			discounted_price: 95,
			description:
				'Cantaloupe juice is a refreshing beverage made from squeezed cantaloupes. It has a sweet and hydrating flavor and is rich in vitamins A and C, as well as antioxidants.',
			rating: 4.4,
			stock: 526,
			category: 'Juices',
			image: '../images/cantaloupe_juice.jpg',
		},
		{
			id: 164,
			name: 'Honeydew Melon Smoothie',
			price: 115,
			discounted_price: 105,
			description:
				'Honeydew melon smoothie is a creamy and refreshing beverage made from blended honeydew melons, yogurt, milk, or juice. It is rich in vitamins A and C, as well as antioxidants.',
			rating: 4.1,
			stock: 511,
			category: 'Juices',
			image: '../images/honeydew_melon_smoothie.jpg',
		},
		{
			id: 165,
			name: 'Grapefruit Juice',
			price: 95,
			discounted_price: 85,
			description:
				'Grapefruit juice is a tangy and refreshing beverage made from squeezed grapefruits. It is rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.3,
			stock: 780,
			category: 'Juices',
			image: '../images/grapefruit_juice.jpg',
		},
	],
	Cereals: [
		{
			id: 166,
			name: 'Corn Flakes',
			price: 50,
			discounted_price: 45,
			description:
				'Corn flakes are a popular breakfast cereal made from toasted corn grits. They are often served with milk and are a good source of carbohydrates and essential vitamins and minerals.',
			rating: 4.1,
			stock: 537,
			category: 'Cereals',
			image: '../images/corn_flakes.jpg',
		},
		{
			id: 167,
			name: 'Oatmeal',
			price: 60,
			discounted_price: 55,
			description:
				'Oatmeal is a nutritious breakfast cereal made from rolled or ground oats. It is high in fiber and protein and can be served with milk, fruit, or nuts for added flavor and nutrition.',
			rating: 4.5,
			stock: 895,
			category: 'Cereals',
			image: '../images/oatmeal.jpg',
		},
		{
			id: 168,
			name: 'Rice Krispies',
			price: 40,
			discounted_price: 35,
			description:
				'Rice Krispies are a crispy breakfast cereal made from rice grains that have been puffed and toasted. They are often served with milk and are a popular choice for children.',
			rating: 4.4,
			stock: 543,
			category: 'Cereals',
			image: '../images/rice_krispies.jpg',
		},
		{
			id: 169,
			name: 'Frosted Flakes',
			price: 55,
			discounted_price: 50,
			description:
				'Frosted flakes are a sweet and crispy breakfast cereal made from corn grits that have been coated with sugar and toasted. They are often served with milk and are a favorite among children.',
			rating: 4.3,
			stock: 755,
			category: 'Cereals',
			image: '../images/frosted_flakes.jpg',
		},
		{
			id: 170,
			name: 'Cheerios',
			price: 45,
			discounted_price: 40,
			description:
				'Cheerios are a popular breakfast cereal made from toasted oats in the shape of small, round rings. They are often served with milk and are known for their heart-healthy benefits.',
			rating: 4.2,
			stock: 808,
			category: 'Cereals',
			image: '../images/cheerios.jpg',
		},
		{
			id: 171,
			name: 'Cocoa Puffs',
			price: 60,
			discounted_price: 55,
			description:
				'Cocoa Puffs are a chocolate-flavored breakfast cereal made from puffed corn grains. They are often served with milk and are a favorite among chocolate lovers.',
			rating: 4.5,
			stock: 802,
			category: 'Cereals',
			image: '../images/cocoa_puffs.jpg',
		},
		{
			id: 172,
			name: 'Lucky Charms',
			price: 65,
			discounted_price: 60,
			description:
				'Lucky Charms are a sweet and colorful breakfast cereal made from toasted oats with marshmallow shapes. They are often served with milk and are popular among children.',
			rating: 4.3,
			stock: 670,
			category: 'Cereals',
			image: '../images/lucky_charms.jpg',
		},
		{
			id: 173,
			name: 'Froot Loops',
			price: 55,
			discounted_price: 50,
			description:
				'Froot Loops are a fruity breakfast cereal made from corn flour with artificial fruit flavors and colors. They are often served with milk and are a favorite among children.',
			rating: 4.3,
			stock: 894,
			category: 'Cereals',
			image: '../images/froot_loops.jpg',
		},
		{
			id: 174,
			name: 'Honey Nut Cheerios',
			price: 50,
			discounted_price: 45,
			description:
				'Honey Nut Cheerios are a sweet and nutty breakfast cereal made from toasted oats with honey and almond flavor. They are often served with milk and are known for their heart-healthy benefits.',
			rating: 4.4,
			stock: 619,
			category: 'Cereals',
			image: '../images/honey_nut_cheerios.jpg',
		},
		{
			id: 175,
			name: 'Raisin Bran',
			price: 55,
			discounted_price: 50,
			description:
				'Raisin Bran is a breakfast cereal made from toasted bran flakes with raisins. It is often served with milk and is a good source of fiber and essential vitamins and minerals.',
			rating: 4.3,
			stock: 550,
			category: 'Cereals',
			image: '../images/raisin_bran.jpg',
		},
		{
			id: 176,
			name: 'Cinnamon Toast Crunch',
			price: 60,
			discounted_price: 55,
			description:
				'Cinnamon Toast Crunch is a sweet and cinnamon-flavored breakfast cereal made from toasted squares of corn and rice. It is often served with milk and is a favorite among children.',
			rating: 4.4,
			stock: 974,
			category: 'Cereals',
			image: '../images/cinnamon_toast_crunch.jpg',
		},
		{
			id: 177,
			name: 'Granola',
			price: 70,
			discounted_price: 65,
			description:
				'Granola is a nutritious breakfast cereal made from rolled oats, nuts, seeds, and dried fruits, baked until crisp. It is often served with yogurt or milk and is a good source of fiber and protein.',
			rating: 4.1,
			stock: 780,
			category: 'Cereals',
			image: '../images/granola.jpg',
		},
		{
			id: 178,
			name: 'Special K',
			price: 45,
			discounted_price: 40,
			description:
				'Special K is a lightly toasted breakfast cereal made from rice and wheat flakes. It is often served with milk and is known for its low calorie and high protein content.',
			rating: 4.5,
			stock: 902,
			category: 'Cereals',
			image: '../images/special_k.jpg',
		},
		{
			id: 179,
			name: 'Fiber One',
			price: 55,
			discounted_price: 50,
			description:
				'Fiber One is a high-fiber breakfast cereal made from bran flakes and fiber-rich ingredients. It is often served with milk and is known for its digestive health benefits.',
			rating: 4.3,
			stock: 853,
			category: 'Cereals',
			image: '../images/fiber_one.jpg',
		},
		{
			id: 180,
			name: 'Shredded Wheat',
			price: 40,
			discounted_price: 35,
			description:
				'Shredded Wheat is a classic breakfast cereal made from whole wheat strands. It is often served with milk and is known for its simplicity and natural flavor.',
			rating: 4.5,
			stock: 609,
			category: 'Cereals',
			image: '../images/shredded_wheat.jpg',
		},
		{
			id: 181,
			name: 'Raisin Nut Bran',
			price: 60,
			discounted_price: 55,
			description:
				'Raisin Nut Bran is a hearty breakfast cereal made from bran flakes with raisins and almonds. It is often served with milk and is a good source of fiber and essential vitamins and minerals.',
			rating: 4.5,
			stock: 618,
			category: 'Cereals',
			image: '../images/raisin_nut_bran.jpg',
		},
		{
			id: 182,
			name: 'Wheaties',
			price: 50,
			discounted_price: 45,
			description:
				'Wheaties is a classic breakfast cereal made from toasted whole wheat flakes. It is often served with milk and is known for its iconic brand and sports-themed packaging.',
			rating: 4,
			stock: 987,
			category: 'Cereals',
			image: '../images/wheaties.jpg',
		},
		{
			id: 183,
			name: 'Puffed Rice',
			price: 35,
			discounted_price: 30,
			description:
				'Puffed Rice is a light and crispy breakfast cereal made from rice grains that have been puffed under high pressure. It is often served with milk and is a low-calorie option.',
			rating: 4.2,
			stock: 506,
			category: 'Cereals',
			image: '../images/puffed_rice.jpg',
		},
		{
			id: 184,
			name: 'Quaker Oats',
			price: 40,
			discounted_price: 35,
			description:
				'Quaker Oats is a classic breakfast cereal made from rolled oats. It is often served as oatmeal or porridge with milk or water and is known for its heart-healthy benefits.',
			rating: 4.1,
			stock: 541,
			category: 'Cereals',
			image: '../images/quaker_oats.jpg',
		},
		{
			id: 185,
			name: "Cap'n Crunch",
			price: 55,
			discounted_price: 50,
			description:
				"Cap'n Crunch is a sweet and crunchy breakfast cereal made from corn and oats. It is often served with milk and is a favorite among children.",
			rating: 4.1,
			stock: 926,
			category: 'Cereals',
			image: '../images/capn_crunch.jpg',
		},
	],
};
