export const productsData = {
	Vegetables: [
		{
			id: 1,
			name: 'Bell Pepper',
			price: 70,
			discounted_price: 60,
			description:
				'Bell peppers, also known as sweet peppers, come in various colors such as red, yellow, and green. They are crunchy and sweet, and can be eaten raw or cooked in a variety of dishes.',
			rating: 4.4,
			stock: 836,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/capsicum.jpg',
		},
		{
			id: 2,
			name: 'Carrot',
			price: 60,
			discounted_price: 45,
			description:
				'Carrots are root vegetables that are rich in beta-carotene, which is converted into vitamin A in the body. They are crunchy and sweet when raw and can be cooked in various dishes.',
			rating: 4.1,
			stock: 769,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/carrots.jpg',
		},
		{
			id: 3,
			name: 'Broccoli',
			price: 120,
			discounted_price: 100,
			description:
				'Broccoli is a cruciferous vegetable known for its dense green florets. It is rich in vitamins, minerals, and antioxidants, making it a nutritious addition to any diet.',
			rating: 4.4,
			stock: 767,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/broccoli.jpg',
		},

		{
			id: 4,
			name: 'Cucumber',
			price: 40,
			discounted_price: 35,
			description:
				'Cucumbers are cylindrical green fruits with a mild flavor and high water content. They are often eaten raw in salads or used as a refreshing snack.',
			rating: 4.3,
			stock: 811,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/cucumber.webp',
		},
		{
			id: 5,
			name: 'Cauliflower',
			price: 65,
			discounted_price: 60,
			description:
				'Cauliflower is a versatile vegetable with a mild, slightly nutty flavor. It can be eaten raw, roasted, steamed, or mashed, and is often used as a low-carb alternative to grains and legumes.',
			rating: 4.4,
			stock: 627,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/cauliflower.jpg',
		},
		{
			id: 6,
			name: 'Tomato',
			price: 90,
			discounted_price: 50,
			description:
				'Tomatoes are juicy fruits commonly used as vegetables in cooking. They are rich in lycopene, an antioxidant that has been linked to various health benefits.',
			rating: 4.3,
			stock: 826,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/tomotos.webp',
		},

		{
			id: 7,
			name: 'Potato',
			price: 50,
			discounted_price: 40,
			description:
				'Potatoes are starchy tuberous vegetables that are a staple food in many cuisines around the world. They can be boiled, baked, fried, or mashed, and are used in numerous dishes.',
			rating: 4,
			stock: 645,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/potato.jpg',
		},
		{
			id: 8,
			name: 'Onion',
			price: 45,
			discounted_price: 40,
			description:
				'Onions are aromatic vegetables with layers of flesh surrounding a central core. They are widely used in cooking to add flavor to various dishes.',
			rating: 4.4,
			stock: 511,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/onion.jpg',
		},
		{
			id: 9,
			name: 'Green Beans',
			price: 75,
			discounted_price: 70,
			description:
				'Green beans, also known as string beans or snap beans, are long, slender vegetables with a crisp texture. They can be steamed, stir-fried, boiled, or roasted.',
			rating: 4.5,
			stock: 630,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/beans.jpg',
		},
		{
			id: 10,
			name: 'Cabbage',
			price: 55,
			discounted_price: 50,
			description:
				'Cabbage is a leafy green or purple vegetable with dense leaves that can be eaten raw, cooked, or fermented. It is commonly used in salads, coleslaw, stir-fries, and soups.',
			rating: 4.5,
			stock: 703,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/pink-cabbage.jpg',
		},
		{
			id: 11,
			name: 'Mushroom',
			price: 70,
			discounted_price: 60,
			description:
				'Mushrooms are fungi with a unique flavor and texture. They come in various types, including button, portobello, and shiitake, and can be used in a wide range of dishes, from soups and stir-fries to pizzas and pastas.',
			rating: 4.1,
			stock: 928,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/mushroom.jpg',
		},

		{
			id: 12,
			name: 'Radish',
			price: 40,
			discounted_price: 35,
			description:
				'Radishes are small, crunchy vegetables with a peppery flavor. They come in various colors, shapes, and sizes and can be eaten raw or cooked. Radishes are low in calories and high in fiber, making them a healthy snack or addition to salads.',
			rating: 4.3,
			stock: 726,
			category: 'Vegetables',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/vegetables/radish.jpeg',
		},
	],
	Fruits: [
		{
			id: 100,
			name: 'Apple',
			price: 80,
			discounted_price: 70,
			description:
				'Apples are crisp and juicy fruits with a sweet and slightly tart flavor. They come in various colors and are rich in fiber, vitamins, and antioxidants.',
			rating: 4.1,
			stock: 909,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/apple.jpg',
		},
		{
			id: 101,
			name: 'Banana',
			price: 60,
			discounted_price: 50,
			description:
				'Bananas are creamy and sweet fruits with a soft texture. They are rich in potassium, vitamins, and dietary fiber, making them a healthy snack option.',
			rating: 4.2,
			stock: 520,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/banana.webp',
		},
		{
			id: 102,
			name: 'Orange',
			price: 70,
			discounted_price: 60,
			description:
				'Oranges are citrus fruits with a bright and tangy flavor. They are rich in vitamin C, antioxidants, and fiber, making them a refreshing and nutritious snack.',
			rating: 4.1,
			stock: 960,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/orange.jpeg',
		},
		{
			id: 103,
			name: 'Grapes',
			price: 100,
			discounted_price: 90,
			description:
				'Grapes are small, sweet fruits that grow in clusters on vines. They come in various colors, including green, red, and purple, and are often eaten fresh or used to make wine, juice, or jelly.',
			rating: 4.3,
			stock: 866,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/grapes.webp',
		},
		{
			id: 104,
			name: 'Strawberry',
			price: 120,
			discounted_price: 110,
			description:
				'Strawberries are juicy, red berries with a sweet and slightly tart flavor. They are rich in vitamin C, antioxidants, and dietary fiber, making them a popular and nutritious snack.',
			rating: 4.3,
			stock: 809,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/strawberrys.jpg',
		},
		{
			id: 105,
			name: 'Pineapple',
			price: 150,
			discounted_price: 140,
			description:
				'Pineapples are tropical fruits with a sweet and tangy flavor. They are rich in vitamin C, manganese, and bromelain, an enzyme that may have anti-inflammatory properties.',
			rating: 4.2,
			stock: 798,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/pineapple.jpg',
		},
		{
			id: 106,
			name: 'Mango',
			price: 100,
			discounted_price: 90,
			description:
				'Mangoes are juicy, tropical fruits with a sweet and tangy flavor. They are rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.3,
			stock: 797,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/mango.jpeg',
		},
		{
			id: 107,
			name: 'Watermelon',
			price: 80,
			discounted_price: 70,
			description:
				'Watermelons are large, juicy fruits with a sweet and refreshing flavor. They are high in water content and rich in vitamins A and C, as well as antioxidants.',
			rating: 4.3,
			stock: 968,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/watermelon.webp',
		},
		{
			id: 108,
			name: 'Peach',
			price: 90,
			discounted_price: 80,
			description:
				'Peaches are soft, juicy fruits with a sweet and slightly tangy flavor. They are rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.2,
			stock: 762,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/peach.jpeg',
		},
		{
			id: 109,
			name: 'Pear',
			price: 70,
			discounted_price: 60,
			description:
				'Pears are sweet and juicy fruits with a slightly grainy texture. They come in various colors and are rich in vitamins C and K, as well as dietary fiber.',
			rating: 4.1,
			stock: 877,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/pear.webp',
		},
		{
			id: 110,
			name: 'Plum',
			price: 80,
			discounted_price: 70,
			description:
				'Plums are small, sweet fruits with a smooth, often purple skin and a juicy flesh. They are rich in vitamins A and C, as well as antioxidants and dietary fiber.',
			rating: 4.1,
			stock: 989,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/plum.jpeg',
		},
		{
			id: 111,
			name: 'Cherry',
			price: 100,
			discounted_price: 90,
			description:
				'Cherries are small, round fruits with a sweet and tart flavor. They come in various colors, including red, yellow, and black, and are rich in vitamins, antioxidants, and dietary fiber.',
			rating: 4.4,
			stock: 715,
			category: 'Fruits',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/fruits/cherries.jpg',
		},
	],
	Juices: [
		{
			id: 200,
			name: 'Apple Juice',
			price: 100,
			discounted_price: 90,
			description:
				'Apple juice is a refreshing beverage made from pressed apples. It has a sweet and tangy flavor and is rich in vitamins and antioxidants.',
			rating: 4.4,
			stock: 980,
			category: 'Juices',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/juices/apple-juice.jpeg',
		},
		{
			id: 201,
			name: 'Banana Smoothie',
			price: 120,
			discounted_price: 110,
			description:
				'Banana smoothie is a creamy beverage made from blended bananas and other ingredients such as yogurt, milk, or fruit juice. It is rich in potassium, vitamins, and protein.',
			rating: 4.4,
			stock: 750,
			category: 'Juices',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/juices/banana-smoothie.avif',
		},
		{
			id: 202,
			name: 'Orange Juice',
			price: 90,
			discounted_price: 80,
			description:
				'Orange juice is a refreshing beverage made from squeezed oranges. It has a bright and tangy flavor and is rich in vitamin C and antioxidants.',
			rating: 4,
			stock: 890,
			category: 'Juices',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/juices/orange-juice.webp',
		},
		{
			id: 203,
			name: 'Grape Juice',
			price: 110,
			discounted_price: 100,
			description:
				'Grape juice is a sweet and flavorful beverage made from pressed grapes. It is rich in antioxidants and vitamins and is often enjoyed as a refreshing drink.',
			rating: 4.4,
			stock: 661,
			category: 'Juices',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/juices/grape-juice.webp',
		},
		{
			id: 204,
			name: 'Strawberry Smoothie',
			price: 130,
			discounted_price: 120,
			description:
				'Strawberry smoothie is a creamy and fruity beverage made from blended strawberries, yogurt, milk, or juice. It is rich in vitamin C, antioxidants, and dietary fiber.',
			rating: 4.3,
			stock: 500,
			category: 'Juices',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/juices/strawberry-smoothie.jpeg',
		},
		{
			id: 205,
			name: 'Pineapple Juice',
			price: 120,
			discounted_price: 110,
			description:
				'Pineapple juice is a tropical beverage made from squeezed pineapples. It has a sweet and tangy flavor and is rich in vitamin C, manganese, and bromelain.',
			rating: 4.2,
			stock: 705,
			category: 'Juices',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/juices/pineapple-juice.jpeg',
		},
		{
			id: 206,
			name: 'Mango Smoothie',
			price: 140,
			discounted_price: 130,
			description:
				'Mango smoothie is a creamy and tropical beverage made from blended mangoes, yogurt, milk, or juice. It is rich in vitamins A and C, antioxidants, and dietary fiber.',
			rating: 4,
			stock: 673,
			category: 'Juices',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/juices/mango-smoothie.jpg',
		},
		{
			id: 207,
			name: 'Watermelon Juice',
			price: 100,
			discounted_price: 90,
			description:
				'Watermelon juice is a refreshing beverage made from squeezed watermelons. It has a sweet and hydrating flavor and is rich in vitamins A and C, as well as antioxidants.',
			rating: 4.4,
			stock: 697,
			category: 'Juices',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/juices/watermelon-juice.jpg',
		},
	],

	Dried: [
		{
			id: 401,
			name: 'Almonds',
			price: 50,
			discounted_price: 45,
			description:
				'Almonds are nutrient-rich nuts that are high in protein, healthy fats, and essential vitamins and minerals. They make for a delicious and crunchy snack.',
			rating: 4.8,
			stock: 1200,
			category: 'dried',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/dried/almonds.jpg',
		},
		{
			id: 402,
			name: 'Cashews',
			price: 70,
			discounted_price: 65,
			description:
				'Cashews are creamy and buttery nuts that are packed with vitamins, minerals, and antioxidants. They are a versatile ingredient in both sweet and savory dishes.',
			rating: 4.7,
			stock: 1000,
			category: 'dried',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/dried/Cashews.jpg',
		},
		{
			id: 403,
			name: 'Pistachios',
			price: 80,
			discounted_price: 75,
			description:
				'Pistachios are nutrient-dense nuts that are rich in protein, fiber, and healthy fats. They have a slightly sweet and salty flavor and are a popular snack option.',
			rating: 4.6,
			stock: 900,
			category: 'dried',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/dried/pistachios.webp',
		},
		{
			id: 404,
			name: 'Walnuts',
			price: 60,
			discounted_price: 55,
			description:
				'Walnuts are heart-healthy nuts that are high in omega-3 fatty acids, antioxidants, and vitamins. They have a rich, earthy flavor and are often used in baking and cooking.',
			rating: 4.5,
			stock: 1100,
			category: 'dried',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/dried/walnuts.jpeg',
		},
		{
			id: 405,
			name: 'Pumpkin Seeds',
			price: 40,
			discounted_price: 35,
			description:
				'Pumpkin seeds, also known as pepitas, are crunchy seeds that are rich in protein, iron, magnesium, and zinc. They can be eaten raw or roasted and are a popular snack.',
			rating: 4.4,
			stock: 800,
			category: 'dried',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/dried/pumpkinseeds.jpeg',
		},
		{
			id: 406,
			name: 'Sunflower Seeds',
			price: 30,
			discounted_price: 25,
			description:
				'Sunflower seeds are nutritious seeds that are high in vitamin E, selenium, and healthy fats. They have a mild, nutty flavor and can be eaten as a snack or added to salads and baked goods.',
			rating: 4.3,
			stock: 950,
			category: 'dried',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/dried/sunflower-seeds.webp',
		},
		{
			id: 407,
			name: 'Hazelnuts',
			price: 75,
			discounted_price: 70,
			description:
				'Hazelnuts, also known as filberts, are sweet and buttery nuts with a rich flavor. They are high in healthy fats, vitamins, and minerals, making them a nutritious snack option.',
			rating: 4.6,
			stock: 850,
			category: 'dried',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/dried/Hazlenuts.jpg',
		},
		{
			id: 408,
			name: 'Chia Seeds',
			price: 35,
			discounted_price: 30,
			description:
				'Chia seeds are tiny seeds that are packed with nutrients, including omega-3 fatty acids, fiber, protein, and antioxidants. They can be added to smoothies, yogurt, or oatmeal for a nutritious boost.',
			rating: 4.5,
			stock: 1000,
			category: 'dried',
			image: 'https://ik.imagekit.io/maheshmaddhi/veggieBazaar/dried/chia-seeds.jpg',
		},
	],
};
